### ISSUE TITLE
shtml不替换引用

### ISSUE THREAD

**Issue by Capricair** [hefangshi/fis-postpackager-simple#14]
最近遇到一个问题，前端在写页面的时候，通常会有一些公用部分，比如header，footer，nav之类的，为了方便维护，把html改成shtml，通过引入公用部分，但是打包插件对于shtml只是压缩和打包资源，并不替换页面上的引用，这个问题有什么解决办法吗？

**Comment by hefangshi** [comment]
shtml默认应该也是处理的，你fis的版本多少，估计是版本太老了

**Comment by Capricair** [comment]
fis版本是1.9.30

**Comment by hefangshi** [comment]
你命令用的是fis release而不是其他的？

**Comment by Capricair** [comment]
我自己写的批处理，fis编译是这句：cmd /c fis release -pod ./output，现在已经确定把shtml改为html是正常的，但shtml是不进行替换的

**Comment by hefangshi** [comment]
你这样配置一下再编译看看

```
fis.config.set('project.fileType.text', 'shtml');

fis.config.get('roadmap.path').unshift({
    reg: '**.shtml',
    isHtmlLike: true
});
```

如果可以工作，就把下面一个配置去掉再试试看

**Comment by Capricair** [comment]
在 fileType.text 里追加 shtml 可以，谢谢！

**Comment by hefangshi** [comment]
ok
