### ISSUE TITLE
打包文件名md5值的问题

### ISSUE THREAD

**Issue by qianjunsteve** [hefangshi/fis-postpackager-simple#17]
代码中，md5值是通过合并子文件的文件id来判断的。因此，只改动某一子文件内容，最后的打包文件md5不会改变，这样设计是否不太合理？

**Comment by hefangshi** [comment]
这只是第一级md5值，他代表的是合并的文件序列。你可以继续为打包文件添加FIS基于内容产生的MD5，两者不冲突，也就是最终的文件名会带2个md5串。

**Comment by qianjunsteve** [comment]
多谢
