### ISSUE TITLE
增加功能：autocombine为true时，output文件名跟当前html名称关联

### ISSUE THREAD

**Issue by darkmirrors** [hefangshi/fis-postpackager-simple#9]
@hefangshi 

我想次插件增加一个功能，就是autocombine的output文件名，可以定义到跟当前文件有关联的名称。

增加了如下代码：

```javascript
var arry = [];
for(var key in ret.src){
    arry.push(ret.src[key].filename);
}

var subpath = settings.output.replace('${index}', combineCount)
                    .replace('${name}', arry[0])
                    .replace('${hash}', fis.util.md5(stable(has).join(','), 5))
                 + '.' + fileExt;
```
配置文件：
> fis.config.set('settings.postpackager.simple.output', 'pkg/auto_${name}');

index.html 编译后，得到pkg/auto_index.js。

忘您可以采纳更新，麻烦同时更新到fis-pure中。

**Comment by hefangshi** [comment]
这个是不可行的，因为simple是从项目的整体角度出发，页面A.html与页面B.html如果依赖的资源是一致的，那么是不会打出一个pkg/auto_a.js和pkg/auto_b.js的，而是公用同一个文件。

基于这个逻辑，没有让PKG的名称与页面关联。

**Comment by darkmirrors** [comment]
@hefangshi 

嗯，大部分同意这个逻辑。我加上这个，其实只是想，用autocombine来实现所有引入的js，然后统一打包到一个js里面，这样就可以轻松实现一个页面只引入一个js了。

同时不用再作以下配置，我们只需要在写业务js的时候require其他的js来用就好了。
```javascript
fis.config.set('pack', {
    'pkg/lib.js': [
    	'/lib/mod.js',
        '/modules/underscore/**.js',
        '/modules/backbone/**.js',
        '/modules/jquery/**.js',
        '/modules/vendor/**.js',
        '/modules/common/**.js'
    ]
});
```

**Comment by hefangshi** [comment]
不太建议这样，仔细考虑下simple的用法，其实已经算次优的方案了，能部分解决自动化工作，同时解决了AIO打包过于粗犷的问题。
